name: english_learning_app
description: 一个简单的英语学习App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/word_levels.json
    - assets/data/word_levels_full.json
    - assets/fonts/
  
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Thin.otf
          weight: 100
        - asset: assets/fonts/NotoSansSC-Light.otf
          weight: 300
        - asset: assets/fonts/NotoSansSC-DemiLight.otf
          weight: 400
        - asset: assets/fonts/NotoSansSC-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansSC-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansSC-Bold.otf
          weight: 700
        - asset: assets/fonts/NotoSansSC-Black.otf
          weight: 900
